# Generated by Django 4.0.1 on 2022-02-24 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_remove_blog_dislike_remove_blog_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentblog',
            name='comment_author',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_blog_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentnews',
            name='comment_author',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_news_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
